####################################################################################
#
# Generated by eda_pt_script.tcl	#1
#              eda_pt_conversion.tcl	#1
#              in d:/altera/81/quartus/common/tcl/internal/eda_pt/.
#
# Quartus:  Version 8.1 Build 163 10/28/2008 SJ Web Edition
#
# Project:  8X300_gen2
# Revision: 8X300
#
# Date: Thu May 21 5:04:04 PM Central Daylight Time 2020
#
####################################################################################


set _col3 [ get_ports { \
		clk \
		n_halt \
		n_reset \
		{I[0]} \
		{I[1]} \
		{I[2]} \
		{I[3]} \
		{I[4]} \
		{I[5]} \
		{I[6]} \
		{I[7]} \
		{I[8]} \
		{I[9]} \
		{I[10]} \
		{I[11]} \
		{I[12]} \
		{I[13]} \
		{I[14]} \
		{I[15]} \
		{n_IV_in[0]} \
		{n_IV_in[1]} \
		{n_IV_in[2]} \
		{n_IV_in[3]} \
		{n_IV_in[4]} \
		{n_IV_in[5]} \
		{n_IV_in[6]} \
		{n_IV_in[7]} \
	}]



set _col4 [ get_ports { \
		IO_n_LB_r \
		IO_n_LB_w \
		IO_n_RB_r \
		IO_n_RB_w \
		IO_SC \
		IO_WC \
		{A[0]} \
		{A[1]} \
		{A[2]} \
		{A[3]} \
		{A[4]} \
		{A[5]} \
		{A[6]} \
		{A[7]} \
		{A[8]} \
		{A[9]} \
		{A[10]} \
		{A[11]} \
		{A[12]} \
		{n_IV_out[0]} \
		{n_IV_out[1]} \
		{n_IV_out[2]} \
		{n_IV_out[3]} \
		{n_IV_out[4]} \
		{n_IV_out[5]} \
		{n_IV_out[6]} \
		{n_IV_out[7]} \
		~LVDS41p/nCEO~ \
	}]



set _col0 [ get_ports {clk}]



set _col5 [ get_ports { \
		IO_n_LB_r \
		IO_n_LB_w \
		IO_n_RB_r \
		IO_n_RB_w \
		IO_SC \
		IO_WC \
		{A[0]} \
		{A[1]} \
		{A[2]} \
		{A[3]} \
		{A[4]} \
		{A[5]} \
		{A[6]} \
		{A[7]} \
		{A[8]} \
		{A[9]} \
		{A[10]} \
		{A[11]} \
		{A[12]} \
		{n_IV_out[0]} \
		{n_IV_out[1]} \
		{n_IV_out[2]} \
		{n_IV_out[3]} \
		{n_IV_out[4]} \
		{n_IV_out[5]} \
		{n_IV_out[6]} \
		{n_IV_out[7]} \
		~LVDS41p/nCEO~ \
	}]



set _col1 [ get_ports { \
		clk \
		n_halt \
		n_reset \
		{I[0]} \
		{I[1]} \
		{I[2]} \
		{I[3]} \
		{I[4]} \
		{I[5]} \
		{I[6]} \
		{I[7]} \
		{I[8]} \
		{I[9]} \
		{I[10]} \
		{I[11]} \
		{I[12]} \
		{I[13]} \
		{I[14]} \
		{I[15]} \
		{n_IV_in[0]} \
		{n_IV_in[1]} \
		{n_IV_in[2]} \
		{n_IV_in[3]} \
		{n_IV_in[4]} \
		{n_IV_in[5]} \
		{n_IV_in[6]} \
		{n_IV_in[7]} \
	}]



